services:
  whaticket_backend:
    image: whaticket-backend:latest
    environment:
      - NODE_ENV=${NODE_ENV}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PROXY_PORT=${PROXY_PORT}
      - PORT=${PORT}
      - DOMINIO=${DOMINIO}
      - PURCHASE_KEY=${PURCHASE_KEY}
      - TIMEOUT_TO_IMPORT_MESSAGE=${TIMEOUT_TO_IMPORT_MESSAGE}
      - FLUSH_REDIS_ON_START=${FLUSH_REDIS_ON_START}
      - DEBUG_TRACE=${DEBUG_TRACE}
      - CHATBOT_RESTRICT_NUMBER=${CHATBOT_RESTRICT_NUMBER}
      - BROWSER_CLIENT=${BROWSER_CLIENT}
      - BROWSER_NAME=${BROWSER_NAME}
      - BROWSER_VERSION=${BROWSER_VERSION}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - REDIS_URI=${REDIS_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_OPT_LIMITER_MAX=${REDIS_OPT_LIMITER_MAX}
      - REDIS_OPT_LIMITER_DURATION=${REDIS_OPT_LIMITER_DURATION}
      - CONNECTIONS_LIMIT=${CONNECTIONS_LIMIT}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
    volumes:
      - backend_public:/usr/src/app/public/
    networks:
      - whaticket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  whaticket_frontend:
    image: whaticket-frontend:latest
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}
      - REACT_APP_BACKEND_PROTOCOL=${REACT_APP_BACKEND_PROTOCOL}
      - REACT_APP_BACKEND_HOST=${REACT_APP_BACKEND_HOST}
      - REACT_APP_BACKEND_PORT=${REACT_APP_BACKEND_PORT}
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=${REACT_APP_HOURS_CLOSE_TICKETS_AUTO}
      - REACT_APP_LOCALE=${REACT_APP_LOCALE}
      - REACT_APP_TIMEZONE=${REACT_APP_TIMEZONE}
      - REACT_APP_FACEBOOK_APP_ID=${REACT_APP_FACEBOOK_APP_ID}
      - REACT_ENABLE_SAAS=${REACT_ENABLE_SAAS}
    networks:
      - whaticket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres_whaticket:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ}
    networks:
      - whaticket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  whaticket_redis:
    image: redis:latest
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - whaticket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - whaticket
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  whaticket:
    driver: overlay

volumes:
  postgres-data:
  redis-data:
  backend_public:
